### ISSUE TITLE
Test parallel assembly fails

### ISSUE THREAD

**Issue by joergfunger** [nutofem/nuto#10]
I have currently the problem of a failed test parallel assembly. This test was designed to measure the speedup using 4 processors and requiring at least 0.8*4=3.2 speedup. This works perfectly on a machine that is not used. However, on the jenkins server there are currently many other jobs running, so we do not get the required number of processors to get a reasonable speedup (currently is 2.6 with for processors). Any ideas how to better test parallel performance?

**Comment by TTitscher** [comment]
We could calculate the _current possible_ speedup by measuring a much simpler test problem, e.g. a `for` loop. 
This value is then compared to the NuTo speedup, maybe again with the factor 80%*nproc.
The _current possible_ speedup can be calculated several times: Before, in-between and after the NuTo test.

Additionally, the NuTo test should run faster so we can perform the test several times. As soon as one run produces the desired speedup, the test succeeds.

**Comment by vhirtham** [comment]
I have disabled the test now, because there are linker errors when compiling (These were already present in previous NuTo-versions). Christoph got the same error.

**Comment by Psirus** [comment]
As of commit a6bf213, I've reenabled it, sort of. It is now compiled, but not run (I've added it to the `CMakeScripts/CTestCustom.cmake`). Not a real solution, but at least it not completely abandoned.

**Comment by TTitscher** [comment]
Should be moved to benchmarks

**Comment by Psirus** [comment]
Done in 4e5f9ce.
