### ISSUE TITLE
Manual constraints

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#109]
This is actually the issue of @joergfunger, I'll just write it down :ghost:

## Context

We currently allow arbitrary constrains resulting in a system of constraint equations like
~~~
[T1] (d1) + [T2](d2) = (RHS(t))
~~~
d1 are independent dofs, d2 are dependent dofs and T1 and T2 are coefficient matrices.

We then invert `T2` resulting in
~~~
d2 = -[T2^-1 T1] d1 + [T2^-1] (RHS(t))
~~~
This allows removing d2 from the global system of equations and we only have to solve for the d1 dofs. The matrix `[T2^-1 T1]` is called [mConstraintMatrix](https://github.com/nutofem/nuto/blob/master/src/mechanics/structures/Assembler.h#L96) and the `[T2^-1]` is called [mConstraintMappingRhs](https://github.com/nutofem/nuto/blob/master/src/mechanics/structures/Assembler.h#L114).

## Problem

- The total dofs `d` are separated into `d1` and `d2` via a manually implemented gauss implementation. This works in our custom matrix format and is hard to apply to arbitrary formats.
- The `[T2]` is sparse and the calculation of the inverse is not trivial
- Each evaluation of the `RHS(t)`, requires the matrix multiplication `[T2^-1] (RHS(t))`

## Solution

We restrict the way, constraints can be created in the following way:

1) Each constraint equation must only contain _exactly one_ dependent dof. If you need to define a constraint equation with more than one dependent dof, you have to perform an elimination manually. 
So the following would be invalid:
~~~
1) u0 - u1 = 42  [+ u0 is dependent]
2) u1 - u2 = 12  [+ u1 is dependent] 
~~~
This is invalid since `u0` _and_ `u1` are dependent and both are present in the first equation. Instead, you'll have to manually eliminate one of them in your code, e.g.
~~~
1) u0 - u2 = 54  [+ u0 is dependent]
2) u1 - u2 = 12  [+ u1 is dependent] 
~~~

2) The coefficient in front of the dependent dof term has to be `1`. 

As a result of both restrictions, it is totally clear whether or not a dof is in `d1` or `d2` and `[T2]` will be an identity matrix. Thus we can completely avoid all the [problems](#problem).

**Comment by Psirus** [comment]
Solved in PDE.
