### ISSUE TITLE
Alternative to copying files to the binary directory

### ISSUE THREAD

**Issue by phuschke** [nutofem/nuto#12]
### Problem

Some of the tests require mesh files to run properly. 
### Option 1

One option is to copy the mesh file from the source directory to the current binary directory

```
configure_file(${CMAKE_SOURCE_DIR}/mesh_files/feti_beam.msh ${CMAKE_CURRENT_BINARY_DIR})
```
### Option 2

However, it is much nicer to create a symlink in the current binary directory that points to the original file in the source file

```
execute_process(
  COMMAND "${CMAKE_COMMAND}" "-E" "create_symlink" "${CMAKE_SOURCE_DIR}/mesh_files/feti_beam.msh" "${CMAKE_CURRENT_BINARY_DIR}/feti_beam.msh"
)
```

Unfortunately, symlinks are not supported by all operating systems. 
### Urgency

Very low...

**Comment by Psirus** [comment]
This has been done in 2fe96fc47, so closing it.
