### ISSUE TITLE
Remove Stucture* from Elements

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#15]
## Problem:
- Structure is a god class. We decided to use it for a common interface to the whole NuToMechanics lib. OK. But it should only be the interface, not a way for each class to obtain arbitrary information. 
- Dependencies --> compile time 
- ...
### Stucture->GetId()
- mainly (only?) used in Exceptions
- examples:
  - Structure->ElementGetId(*this) 
  - Structure->ConstitutiveLawGetId() 
- Possible Solution1: Storing the ID at the object 
  - this->GetId()
  - law->GetId()
- Possible Solution2: Use other properties to identify the element
  - eElementType GetType()?
  - print this->Info() before throwing 
### Structure->GetLogger()
- only used in Element.Info() = Debug
- Solution: write to std::cout/std::cerr instead of Logger
### Structure->GetNumTimeDerivatives()
- Solution: Add it to the input map...
### Structure->GroupStuff
- used in ContinuumContactElement, that gets a NodeGroupIp and an ElementGroupId and extracts node vectors and element vectors via the strucutre
- Solution: Pass the node vector and element vector directly
### Structure->GetDofStatus()
- only used by ContinuumElement
- Solution: Pass and store the DofStatus(), not the structure
## ToDo:

Discuss the first ->GetId() problem. The rest should be fine, right?

**Comment by Psirus** [comment]
Intially my reaction is: Why does the Element (Law) need to know under which ID the structure has saved it? So I'm strongly leaning towards _Possible Solution2_.

**Comment by TTitscher** [comment]
I am working on that from time to time. Major problem: The visualization of "SECTION", "ELEMENT", "CONSTITUTIVELAW" visualizes the ID. Here my proposed "possible solution 2" can not be applied. Any thoughts?

**Comment by Psirus** [comment]
I know this can't be applied immediately to the current implementation, but I'd probably do something like this:

```
 Structure::Visualize()
 {
      for(auto element : mElementMap)
          element.second()->VisualizeElement(element.first())
 }
```

i.e., giving these Ids by parameter to the visualize function of the element.

**Comment by Psirus** [comment]
Done in adc4b2413fcff. Further work is needed to visualize sections and laws again though. Maybe we should open a new issue?
