### ISSUE TITLE
NuToContitutiveLaw lib?

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#16]
Just a question. Should we build a NuToConstitutiveLaw lib? Currently the unit tests for the constitutive laws need the whole NuToMechnics lib. That is not necessary. (Why link elements, or time integration schemes to my simple unit test for LinearElastic?)

I would answer that question with: Yes. So, follow up question: What should be included?
-ConstitutiveLaws
-StaticData
-IOBase/IOMaps

What do you think?

(The ideal situation would be to only link some chosen *.cpp files. But it will take a while to remove dependencies...)

**Comment by Psirus** [comment]
Meh. You already know the ideal situation. What do we gain in the meantime by replacing _Suboptimal-Solution-a_ by _Still-suboptimal-yet-slighty-improved-solution-b_? I'd say we wait; it's not like the linking takes ages.
