### ISSUE TITLE
Combination of different Lobatto interpolations not possible

### ISSUE THREAD

**Issue by potto1** [nutofem/nuto#19]
E.g. the combination of EQUIDISTANT1 for coordinates and LOBATTO2 for displacements is not possible, since the LOBATTO node ordering is not reflected in the array 'mNodeIndices' (InterpolationBase).

**Comment by potto1** [comment]
Fixed 'mNodeIndices' but still get wrong stresses

**Comment by TTitscher** [comment]
The bug was caused by the wrong integration type. Setting it manually fixed the problem.
