### ISSUE TITLE
Replace enums with enum classes (strongly typed enums)

### ISSUE THREAD

**Issue by phuschke** [nutofem/nuto#2]
### Stroustrup:

http://www.stroustrup.com/C++11FAQ.html
The enum classes ("new enums", "strong enums") address three problems with traditional C++ enumerations:
- conventional enums implicitly convert to int, causing errors when someone does not want an enumeration to act as an integer.
- conventional enums export their enumerators to the surrounding scope, causing name clashes.
- the underlying type of an enum cannot be specified, causing confusion, compatibility problems, and makes forward declaration impossible.

Example:
enum classs ("strong enums") are strongly typed and scoped:

```
enum Alert { green, yellow, orange, red }; // traditional enum

enum class Color { red, blue };   // scoped and strongly typed enum
                                  // no export of enumerator names into enclosing scope
                                  // no implicit conversion to int
enum class TrafficLight { red, yellow, green };

Alert a = 7;              // error (as ever in C++)
Color c = 7;              // error: no int->Color conversion

int a2 = red;             // ok: Alert->int conversion
int a3 = Alert::red;      // error in C++98; ok in C++11
int a4 = blue;            // error: blue not in scope
int a5 = Color::blue;     // error: not Color->int conversion

Color a6 = Color::blue;   // ok
```

**Comment by TTitscher** [comment]
Sounds reasonable. Personally, I find the longer access to the enum classes annoying. So instead of
`Node::DISPLACEMENTS`
you would have to write 
`Node::eDof::DISPLACEMETS`

But I could live with that...

**Comment by phuschke** [comment]
Well, the namespace Node is not really necessary anymore. Instead, we can put all enum classes in a single file under the namespace NuTo. Enum classes guarantee safety.

Access would be 

`NuTo::eDOF::DISPLACEMENTS`

instead of 

`NuTo::Node::DISPLACEMENTS`

which makes more sense to me anyway.

**Comment by vhirtham** [comment]
Done! All changed!
