### ISSUE TITLE
Activate more compiler warnings

### ISSUE THREAD

**Issue by Psirus** [nutofem/nuto#21]
There are additional warnings that can be enabled in gcc and clang. In particular, I'm thinking of
`-Wextra` in both clang and gcc, which warns if
> - a base class is not initialized in the copy constructor of a derived class,
> - an empty body occurs in an if, else or do while statement,
> - the return type of a function has a type qualifier such as `const`
> - an automatic variable is used without first being initialized
> - a function parameter is unused aside from its declaration

`-Weffc++` in gcc
> Warn about violations of the following style guidelines from Scott Meyers' Effective C++ series of books:
> 
> - Define a copy constructor and an assignment operator for classes with dynamically-allocated memory.
> - Prefer initialization to assignment in constructors.
> - Have operator= return a reference to *this.
> - Don't try to return a reference when you must return an object.
> - Distinguish between prefix and postfix forms of increment and decrement operators.
> - Never overload &&, ||, or ,.

and `-Wdocumentation` in clang:
> Clang parses Doxygen and non-Doxygen style documentation comments and attaches them to the appropriate declaration nodes. By default, it only parses Doxygen-style comments and ignores ordinary comments starting with // and /*.
> `-Wdocumentation`:
> Emit warnings about use of documentation comments. This warning group is off by default.
> This includes checking that \param commands name parameters that actually present in the function signature, checking that \returns is used only on functions that actually return a value etc.

Both of them would be helpful, I think, but activating them right now, we would be drowning in warning messages. Maybe we can have a small coding sprint for each of them.

- [ ] `-Wdocumentation`
- [x] `-Weffc++`
- [x] `-Wextra`

**Comment by Psirus** [comment]
I took a preliminary look at the output of both settings. Many of the warnings were caused by the `FullMatrix` and the `Structure`, so maybe it's easier just to wait until we've removed them.

**Comment by phuschke** [comment]
**Progress**
- [x] `-Wextra`
Enabled with commit 51dc3eb

- [x] `-Weffc++`

> -Weffc++ is not very useful since it is mostly based on the first edition of the book Effective C++, many of whose recommendations were improved in the second edition
[Best GCC warning flags for compiling C++](http://www.artificialworlds.net/blog/2014/07/18/best-gcc-warning-flags-for-compiling-c/)

**Pending:**
- [ ] `-Wdocumentation`

**Comment by phuschke** [comment]
In case you are wondering why there are still so many warnings. Here is an example:
~~~    template <int TRows>
void AssertSth(Input)
{
#ifndef NDEBUG
        // code
#endif
}
~~~
**What should we do about those functions?** 
I guess the proper way is to only declare the function for debug builds but that would mean that we have to write
~~~
#ifndef NDEBUG
       AssertSth(Input)
#endif
~~~

whenever we want to use the function which is annoying.

**Comment by Psirus** [comment]
In the case of these debugging assertions, I think they should not be part of the class, but rather macros like this:
~~~cpp
#define ASSERT_IS_VECTOR(vector, rows)\
    assert(dynamic_cast<const ConstitutiveVector<rows>*>(&vector) != nullptr);
~~~
which you can than use just like normal assertions:
~~~cpp
    EngineeringStrain<1> strain({1.0});
    ASSERT_IS_VECTOR(strain, 1); // will not fail
    ASSERT_IS_VECTOR(strain, 2); // will fail
~~~
