### ISSUE TITLE
Remove `ElementShapeFunctions.h/cpp`

### ISSUE THREAD

**Issue by Psirus** [nutofem/nuto#210]
I think this `ElementShapeFunctions.h/cpp` file is way to big, and collects all shape functions *for no good reason*. And it shows in names like `DerivativeShapeFunctionsTriangleOrder1`, which could just be named `DerivativeShapeFunctions` at the appropriate interpolation class. So I think moving that there is the nicer approach. In 23b8c23a I have tried that for `TriangleLinear`. Does anyone see a problem with continuing that?

**Comment by TTitscher** [comment]
I am not sure about this one: 
- Ok, this class is definitely to big. 
- But it is one of the few files that survived the PDE transition. 
- It defines N,B, nodal vales as fixed size Eigen matrices. This avoids dynamic allocation(!) and provides slightly faster algorithms (up to a certain size). So they can be reused if you try to write own as-fast-as-possible components. To match the `InterpolationSimple` interface, these will be dynamic.

What if, for now, we provide them as static functions in the corresponding classes like:
~~~cpp
// class InterpolaitonTriangleLinear
static Eigen::Fix ShapeFunctions(ip){...}

Eigen::Dynamic GetShapeFunctions(ip) const override
{
return ShapeFunctions(ip);
}
~~~
The big file is gone, the change is also mainly copy-paste and we keep the option on fixed size calculations.
__edit:__ Plus, we would have them available as static functions, which can be handy, e.g. [in tests](https://github.com/nutofem/nuto/commit/23b8c23a41252b53f2b43f0b320369737a465f1f#diff-efb997cb4ef30e76f06623a34a6d3ec5R68)

**Comment by Psirus** [comment]
It adds a bit of extra code, since everything is now there twice (see [InterpolationTriangleLinear.h](https://github.com/nutofem/nuto/blob/remove_shapefunctions/src/mechanics/interpolation/InterpolationTriangleLinear.h) and [InterpolationTriangleLinear.cpp](https://github.com/nutofem/nuto/blob/remove_shapefunctions/src/mechanics/interpolation/InterpolationTriangleLinear.cpp)), but I think its fine.

**Comment by joergfunger** [comment]
Why can't these methods that return shape functions and derivatives be always static?

**Comment by TTitscher** [comment]
They have to implement the [`InterpolationInterface`](https://github.com/nutofem/nuto/blob/PDE_reviewed/src/mechanics/interpolation/InterpolationSimple.h). And virtual methods cannot be static.

**Comment by pmueller2** [comment]
#250

**Comment by pmueller2** [comment]
The files are deleted in #250. Most content moved to the respective interpolation classes. 
- shape functions for BoundaryElements were not used and have been removed.
- iga bezier extraction code was not used and was removed (I talked to Peter about this)
