### ISSUE TITLE
Remove NuTo::FullMatrix

### ISSUE THREAD

**Issue by Psirus** [nutofem/nuto#22]
We're heavily mixing `NuTo::FullMatrix` and `Eigen::Matrix` methods all over the code. The `FullMatrix` is now just a (unnecessary) wrapper. Using Eigen directly might even improve the performance.

The same thing is probably true for `ConstitutiveMatrix`, no?

**Comment by TTitscher** [comment]
IMO we should solve the issue with `ConstitutiveMatrix` when dealing with the PDE class. Maybe, it can be removed...
As for the python interface: @Psirus: You told me about a Eigen <- SWIG -> numpy wrapper thing. Can you link that?

**Comment by Psirus** [comment]
It's a sort of compilable example of how to do this wrapping in SWIG, and not really "another wrapper". You can find it [here](https://github.com/rdeits/swig-eigen-numpy).

**Comment by Psirus** [comment]
As of 67de563, this is done.
