### ISSUE TITLE
Improve Python interface

### ISSUE THREAD

**Issue by Psirus** [nutofem/nuto#23]
The python interface has been neglected for a while, but would be a nice addition to NuTo. Let's make a couple of improvements to make it useful and fun again.

- [x] seperate the wrapper code from the C++ code
- [ ] ~~create docstrings from Doxygen comments~~
- [x] provide proper support for numpy, for an example [see here](https://github.com/rdeits/swig-eigen-numpy)
- [x] remove the `ENABLE_NUMPY` option
- [x] enabling passing python lists where std::vectors are expected
- [ ] export the enums, see also #27 
- [x] Python3 support

**Comment by Psirus** [comment]
I had started working on creating the docstrings from Doxygen comments using doxy2swig, but it seems that SWIG 3.1 will be able to do exactly that with no further code. Therefore, I don't feel inclined to work on it and add further code to NuTo. If you want to see it in action now, you can compile [this SWIG branch](https://github.com/vadz/swig/tree/doxygen) yourself.

**Comment by Psirus** [comment]
I've just created a branch for Python 3, to be found [here](https://github.com/nutofem/nuto/tree/python3). Surprisingly, it took only little changes to make it work with Python 3. Would anyone mind if we switch from Python 2 to 3?

**Comment by joergfunger** [comment]
What exactly are the advantages / disadvantages of using python 2 vs. 3?

Am 10.02.2017 12:33 PM schrieb "Christoph Pohl" <notifications@github.com>:

**Comment by Psirus** [comment]
From [the python wiki](https://wiki.python.org/moin/Python2orPython3)
> 
> Short version: Python 2.x is legacy, Python 3.x is the present and future of the language
> 
> Python 3.0 was released in 2008. The final 2.x version 2.7 release came out in mid-2010, with a statement of extended support for this end-of-life release. The 2.x branch will see no new major releases after that. 3.x is under active development [...]. This means that all recent standard library improvements, for example, are only available by default in Python 3.x.
> [...]
> The most drastic improvement is the better Unicode support (with all text strings being Unicode by default) as well as saner bytes/Unicode separation.
> 
> Besides, several aspects of the core language (such as print and exec being statements, integers using floor division) have been adjusted to be easier for newcomers to learn and to be more consistent with the rest of the language, and old cruft has been removed (for example, all classes are now new-style, "range()" returns a memory efficient iterable, not a list as in 2.x).

**Comment by Psirus** [comment]
Python 3 suppport was merged with 63b9c18acf9be6b1ebe18461842b130e2691ef1d

**Comment by TTitscher** [comment]
I suggest closing this topic, good job! The only remaining bullet point is "export enum". And we should replace that with "remove enums" or rather "change creational pattern", which will mostly be handled by upcoming changes regarding the "class PDE" or "split up structure".

**Comment by Psirus** [comment]
Why don't you bloody do it then? :grimacing: :kissing_heart:
