### ISSUE TITLE
Dof-Class

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#25]
We currently have the `enum class eDof` that is often used as the key to `std::map` or the parameter to `std::set` containing some properties. 
~~~cpp
// from DofStatus.h
std::map<Node::eDof, int> mNumActiveDofs;
std::map<Node::eDof, int> mNumDependentDofs;
std::set<Node::eDof> mDofTypes;
std::set<Node::eDof> mActiveDofTypes;
std::set<Node::eDof> mSymmetricDofTypes;
~~~

IMO a class will be a more straight-forward option.
~~~cpp
class Dof
{
  std::string mName;
  int numActive;
  bool mIsSymmetric;
 // ...
};
~~~

Some random thoughts:
- requires a lot of changes to the code
    - loop/switch pattern over all dof types has to be removed (IMO good)
- it is not restricted to predefined enum values (possible to add dof types in your main file / python)
- physics/PDE does not depend on a name
    - e.g. `eDof::Temperature` is fixed to specific PDE. If you want to solve another temperature PDE, you would have to define `eDof::Temperature2` or a new element or something
- the `class PDE` can define its own `Dof` objects
- reading this, it is quite closely related to the PDE class...

Anyways. What do you think? What problems do you see?

**Comment by Psirus** [comment]
Sounds reasonable, especially if we want the PDEs to be "div v = 0" rather than "balance of linear momentum". Hardcoding the physical meaning would be counterintuitive in that case.

In your alternative, you would save a `std::container<Dof>` instead of a `DofStatus` at the structure, right?

**Comment by TTitscher** [comment]
Ideally, I want to avoid saving things at the structure. :) Another topic, sorry. 

This strongly depends on the design. It has to be saved on a structure-like object indeed. It could be a member of `Assembler`, since the status [*active/symmetric/number*] may only be interesting for the global matrices.

**Comment by TTitscher** [comment]
The dof class is basically implemented as
~~~cpp
struct DofType
{
    std::string mName;
    int mId;
    int mNumDofsPerNode;
};
~~~

In an preoptimization attempt, we always pass/save this object as a reference. String should be expensive and so on. Due to the "small string optimization" (<16 chars) however, there is _very_ little overhead from passing the object by value compared to pass by reference. And we should have enough memory to store the objects (say, 16 byte?) by value as often as we want. How do we deal with this kind of stuff in the future?

**Comment by Psirus** [comment]
Solved in PDE.
