### ISSUE TITLE
Remove NuTo::SparseMatrix

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#26]
# Problems
I just think that implementing such a high performance data structure manually cannot compete with existing implementations.

# Solution

Use an alternative:
- [`Epetra`](https://trilinos.org/docs/dev/packages/epetra/doc/html/classEpetra__FECrsMatrix.html) from Trilinos
- [`Eigen::SparseMatrix`](https://eigen.tuxfamily.org/dox/group__TutorialSparse.html)

Both offer a uniform interface to some solvers.

# Eigen

- provides intuitive interface
    - operators *,+,-, ...
    - different views, block operators
    - [have a quick look here](https://eigen.tuxfamily.org/dox/group__TutorialSparse.html)
    - just nice overall
- There were some doubts about the assembly performance. So have a look here:

## Assembly Benchmark

NuTo-Structure with dummy element matrices. The real global dof numbers were used (connectivity). They were pre-calculated and not part of the benchmark.

### 3D Bricks order 1

|   NumElements   | NuTo [s] | Eigen [s] | NuTo [MB] | Eigen [MB] |
|:---------------:|:--------:|:---------:|:---------:|:----------:|
|    10x10x10     |  0.013   |   0.011   |     3     |     8      |
|    10x10x100    |  0.185   |   0.117   |    31     |     87     |
|   10x10x1000    |   1.40   |   1.133   |    313    |    878     |
|   10x10x5000    |   6.70   |   5.45    |   1567    |    4394    |
| **10x10x10000** |  13.39   |   31.07   |   3135    |    8789    |

### 3D Bricks order 2

|  NumElements   | NuTo [s] | Eigen [s] | NuTo [MB] | Eigen [MB] |
|:--------------:|:--------:|:---------:|:---------:|:----------:|
|    10x10x10    |  0.131   |   0.104   |    26     |     54     |
|   10x10x100    |  1.241   |   0.812   |    257    |    549     |
|   10x10x1000   |  13.87   |   8.43    |   2571    |    5493    |
| **10x10x2000** |  28.39   |   38.35   |   5142    |   10986    |

# Discussion

- Use `Eigen::SparseMatrix`?
- Do we care about the memory overhead? (Factor 2..3 depending on the connectivity)
    - Alternative: `NuTo::SparseMatrixCSRVector2` and `MaximumIndependentSet` as a pure assembly format. With only `AddValue(...)` and `ExportToEigenSparse()`.
- have a look at alternatives? Epetra?

**Comment by TTitscher** [comment]
Maybe to those who are wondering why the `Triplet`-vector is *only* 2 to 3 times bigger. The `NuTo::Vector2` consists of two vectors per matrix row. Each vector is equivalent to three pointers/doubles. That means a default size of 6 doubles / 12 ints per row. 

I suspect that we can optimize this Vector2 format even more. 
- memory: one `vector<pair<int, double>>` instead of two separate `vector<int>` and `vector<double>`
- performance: 
    - resize row vectors less often ( call `vector.reserve(someReasonableLength))
    - consider a *linear* search instead of a *binary* search for small number of elements

We would need to find an efficient conversion from NuTo::Vector2 to Eigen::Sparse though.

- Eigen::SparseMatrix <--> SWIG <--> scipy.sparse ?

**Comment by Psirus** [comment]
Just to revive this issue: I watched a [lightning talk at CppCon](https://youtu.be/8jbt-5Qub9E) (watch it, it's only 4.5 minutes) a little while ago that I thought was quite applicable to this problem. Basically you have an interface as a template of its implementation. This allows you to
- get rid of the vtable lookup (`matrix.AddValue` probably happens a couple million times on even a medium sized problem) and get more compiler optimizations, because it's all static
- you can have default implementations in the base for functionality that an implementation might not have (in particular, our base class could retain e.g. the `Gauss` function needed for the constraints, because I'm quite sure that PeTSC/Epetra/Eigen don't supply that)


Applied to the SparseMatrix it would look something like this:
~~~cpp
template <typename Implementation>
class SparseMatrixInterface
{
public:
    // required, "baseline" functionality
    void AddValue(int row, int col, double value)
    {
        impl.AddValue(row, col, value); // gets inlined
    }

    int GetNumRows()
    {
        return impl.GetNumRows();
    }


    // optional functions; may be implemented, e.g. for better performance
    // default provided by this class
    void AddValues(std::vector<int> rows, std::vector<int> cols, std::vector<double> values)
    {
        AddValues(rows, cols, values, has_add_values<Implementation>{});
    }

    void Gauss(Eigen::MatrixXd, std::vector<int>&, std::vector<int>&, double)
    {
        // same as with AddValues
    }

private:
    void AddValues(std::vector<int> rows, std::vector<int> cols, std::vector<double> values, std::true_type)
    {
        impl.AddValues(rows, cols, values); // uses touple insertion from PeTSC, Epetra, whatever
    }

    // fallback if implementation only has scalar insertion
    void AddValues(std::vector<int> rows, std::vector<int> cols, std::vector<double> values, std::false_type)
    {
        for (int i = 0; i < rows.size(), ++i)
            impl.AddValue(rows[i], cols[i], values[i]);
    }

    // unlikely, but hey
    void Gauss(Eigen::MatrixXd, std::vector<int>&, std::vector<int>&, double, std::true_type)
    {
        // call implementation version of Gauss
    }

    // provide default
    void Gauss(Eigen::MatrixXd, std::vector<int>&, std::vector<int>&, double, std::false_type)
    {
        // do what we usually do
    }

    Implementation impl;
};
~~~

We could provide multiple implementations, like PeTSC, Epetra, Eigen and even NuTo::Vector2 and select one at compile time `using SparseMatrix = SparseMatrixInterface<Epetra>;`.

**Comment by TTitscher** [comment]
Certainly a nice feature. For the future, I suggest. My idea for a roadmap.

- Convert Gauss to a free function with Eigen::Sparse in its signature. Internally, we can convert to and from our own CSR format to not bother with the actual implementation. This can be optimized later.
- carefully think about the assembly and the performance issues regarding both memory and speed. 
- Do it. 
- think about a generic wrapper for other Matrix types.

**Comment by joergfunger** [comment]
I nice feature, but that somehow conflicts with the idea of @TTitscher in #57 or in this issue not to use self implemented operations? Even though most of the functionality would be inlined we would still have to implement all operations separately (*, + , +=,  ....) and also with different inputs (* with all possible eigen::matrices such to deal with this lazy evaluation).

**Comment by TTitscher** [comment]
The (+, -, ...) issue will be resolved, if we manage to eliminate calculations with the global matrices. In this case, #57 only applies to global vectors, e.g. in explicit time integration.

**Comment by Psirus** [comment]
Well sure, I'd like to not implement anything, but alas
- the `Gauss` function is in there now; if you don't remove it/make it a free function you still need it as a matrix member
- if you want to use different implementations with a unified interface, then yes, you need to implement the *wrappers* for all operations separately

The alternative is to limit yourself to one implementation.

**Comment by Psirus** [comment]
Solved in PDE.
