### ISSUE TITLE
Remove string wrapper functions for functions taking enums

### ISSUE THREAD

**Issue by Psirus** [nutofem/nuto#27]
There are quite a few functions in the structure that basically do
~~~.cpp
int SomeFunction(std::string input)
{
    eSomeEnum enum_input = mapStringToEnum(input);
    return SomeFunction(enum_input);
}
~~~

With the move to the enum classes, they are no longer necessary, because [Swig can handle enum classes](http://www.swig.org/Doc3.0/CPlusPlus11.html#CPlusPlus11_strongly_typed_enumerations). Getting rid of them avoids duplicate code, the cumbersome stringToEnum maps and a lot of `#ifndef SWIG` preprocessor stuff. 

Also, the Python interface becomes much nicer, because you can then have autocompletion etc.

On the other hand, do you think this is even necessary as we move towards #24 ?

----

Here is a short list of most of them in the structure (I think); let's do them piece by piece as we do other stuff.

- [ ] NodeCreateDOFs
- [ ] InterpolationTypeCreate
- [ ] InterpolationTypeSetIntegrationType
- [ ] InterpolationTypeAdd
- [ ] AddVisualizationComponent
- [ ] ElementGetStaticIPData
- [ ] ConstraintGetLinearConstraints
- [ ] ConstraintLinearEquationCreate
- [ ] ConstraintLinearEquationAddTerm
- [ ] ConstitutiveLawCreate
- [ ] ConstitutiveLawSetParameter*
- [ ] ConstitutiveLawSetDamageLaw
- [ ] SectionCreate
- [ ] GroupCreate
- [ ] GetNumDofs
- [ ] GetNumActiveDofs
- [ ] GetNumDependentDofs
- [ ] DofTypeSetIsActive
- [ ] DofTypeSetIsConstitutiveInput

**Comment by TTitscher** [comment]
Lets solve this by removing unnecessary enums. See #23.
