### ISSUE TITLE
Neumann boundary conditions

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#28]
The specific case of Neumann boundary conditions for the mechanics problem is currently implemented in mechanics/loads/... including
- node forces
- surface loads
    - pressure (normal to surface)
    - *const direction* (specific direction)

## Problems

- hardcoded for the mechanics problem ("forces")
- no body forces (volume loads) available
- Duplicate code. The calculation of the surface loads is an integration over a boundary and already implemented in `ContinuumBoundaryElement` 
- Limited integration types. The `Prism3D` (*wedge*) element requires different interpolation types for each surface since it has triangular surfaces **and** quad surfaces. The integration is currently picked automatically in the `LoadSomething` methods based on the type and interpolation order of the *base* element. No user input allowed
- No consistent way to apply boundary conditions in general
    - diriclet (displacements) --> `Constraints`
    - neumann (forces) --> `Load`
    - robin (Sping?) --> custom element or boundary element

## Solution

???

## Discussion

Moving everything to `ContinuumBoundaryElement` and `ContinuumElement` is IMO not an option. These classes are already too big
- additional members like "mDirection" for the load direction are not needed in the default case
- hard to avoid duplicate code when creating a new element types for that purpose

Maybe we could solve it by separating the interpolation/integration from the physics. This might be done during solving issue #3 and introducing `class PDE`... More ideas?

**Comment by joergfunger** [comment]
I totally agree with the current problem. My idea would be to implement
boundary elements the way (similar for the continuum elements with the new
pde concept) that only store interpolation types, nodes, integration points
and calculate the corresponding shape functions and derivatives. Everything
else is done in the pde class.
The surface forces (Neumann bc) could than be just another "pde class" that
provide a contribution to the residual - maybe we do not even have to
separate between internal and external forces, but only between residual
contributions that depend on the current active dofs( and thus have to be
recalculated) and those, which are constant (and can be used similar to the
external force now).

2017-01-17 15:01 GMT+01:00 TTitscher <notifications@github.com>:

**Comment by TTitscher** [comment]
I really like that *simple Element + PDE* concept. Maybe we should start working on that soon. A lot of issues boil down to that...

> The surface forces (Neumann bc) could than be just another "pde class" that
provide a contribution to the residual

Intuitively, the boundary conditions are part of the PDE. But not all elements of a specific PDE type need the additional boundary terms. So we should keep that in mind when designing the PDE classes. (e.g. a split in `PDE-Domain` and `PDE-Boundary`) 

Another kind of BCs: Nonlinear Constraints. They had been implemented using [Lagrange multipliers](https://en.wikipedia.org/wiki/Lagrange_multiplier). This feature was removed during the implementation of the dof-separated containers, because the Lagrange multipliers are like a new degree of freedom (with its own `Gradient` and `Hessian`). @phuschke uses some kind of Lagrange multipliers in the FETI method. Do we want re-implement it in a more general way? How? As a LagrangeMultiplierElement?

**Comment by Psirus** [comment]
Solved in PDE.
