### ISSUE TITLE
Element compatibility checking

### ISSUE THREAD

**Issue by Psirus** [nutofem/nuto#31]
In my quest to crack down on enums, I've noticed that one of the main purposes of the `ElementEnum` for example is to check compatibility with the constitutive law or the integration type.

At first I thought: lets replace the enum with RTTI and let the compiler help me: I.e. instead of `case eElementType::CONTINUUMELEMENT: return true;` do `if (typeid(elementPtr) == typeid(ContinuumElement<2>)) return true;`, which would be better, but still suffer from a couple of problems.

One, it is not conceptually clear (at least to me) if the element should check whether it is compatible with an integration type, or the integration type should check whether it is compatible with an element. I could move this logic to a separate `CompatibilityChecker`, but ...

I think this is the wrong approach anyway. For one thing we would like to move in a direction where you can define your element/constitutive law/integration type outside of the library, and having such a check would be a major impediment.  For another, we should check properties, not classes. E.g. the dimension of the integration type and element should agree (currently, the `CheckElementCompatiblity` is not going to complain if you add a 3D integration to a 2D element).

And last but not least this would enable us to let the compiler help. Checking if the dimension is the same could theoretically be done at compile time.

I've created a branch where I've tried (dynamic) dimension checking for the integration types, see [here](https://github.com/nutofem/nuto/tree/element_compatibility). Most of tests pass, except for things concerning the boundary element. For example in `MoistureTransport`, there seems to be a 2D boundary element where a 1D integration type is being tried. Maybe someone with more experience with the boundary elements could take a look?

**Comment by TTitscher** [comment]
You are right about the 2D boundary element with a 1D integration type. IMO the local dimension of a 2D boundary element should be 1 anyways. I fixed that in 686791ec92635df4a7b72b519dd8378fb8af076a and it works.

I'm not so sure about removing the serialize stuff though.

**Comment by Psirus** [comment]
Done. The enum is gone, as are all the `CheckElementCompatibilty` functions as of  b59c885.
