### ISSUE TITLE
ApplyCMatrix sign confict

### ISSUE THREAD

**Issue by pmueller2** [nutofem/nuto#33]
There are two conflicting implementations for the application of a C matrix to a StructureOutputBlockVector in /src/mechanics/structures/StructureOutputBlockVector.cpp
differing in a sign.

ApplyCMatrix(BlockFullVector<double>\& rResidual, const BlockSparseMatrix\& rCmat)
uses 
f_modified = f_J - C * f_K

ApplyCMatrix(const BlockSparseMatrix\& rCmat)
uses 
f_modified = f_J + C * f_K

According to codecov the relevant line of the second version (with the +)  is not tested, probably because there are no interacting constraints in tests using this function (this line is skipped then)

The sign of the first version was changed to minus by phuschke but without comment

According to the text in the Developer documentation "Handling of constraints in NuTo" the minus sign should be correct.

**Comment by Psirus** [comment]
What is the status here? I don't feel qualified to handle this.

**Comment by joergfunger** [comment]
I think the minus sign should be correct - which is also supported by the fact that this is the only version that seems to be tested.

**Comment by pmueller2** [comment]
Ok, so the sign will be changed to minus. Then both methods do almost the same except that the second version changes the J component in place and the first writes it to rResidual. Maybe it would the be better to change the first version so that it returns a BlockFullVector instead of void.

**Comment by Psirus** [comment]
I'd vote to get rid of the second, inplace version and make the first (commonly used one) a free function; it just doesn't need to be a member of `StructureOutputBlockVector`. So the interface would be
~~~cpp
BlockFullVector<double> ApplyCMatrix(const StructureOutputBlockVector& vec,
                                     const BlockSparseMatrix& cMat);
~~~
and if someone needs to modify the vector itself, they can still do `x.J = ApplyCMatrix(x, cMat)`.

**Comment by joergfunger** [comment]
The problem with a free function is the currently used HasInteractingConstraints that is currently still used #56. This has to be solved first when making it a free function.

**Comment by Psirus** [comment]
Why is that a problem? `J` is a public member, `GetDofStatus()` is a public member of that, and `HasInteractingConstraints()` is in turn a public member of that.

**Comment by Psirus** [comment]
Commit fbea3f2d1f5ab7e3691c1e05bd7af14be30238c3 moved the `ApplyCMatrix` function for vectors to the `Assembler`, where it is a static function. This helped in cleaning up `Newmark`. The version for matrices is still in the `StructureOutputBlockMatrix`, but there is no sign conflict, so this issue can be closed once the Newmark refactoring branch is merged.
