### ISSUE TITLE
Variable number of integration points

### ISSUE THREAD

**Issue by potto1** [nutofem/nuto#37]
So far each Gauß integration type is represented in a special class than handles a quadrature with a certain amount of quadrature points. At least for 1D and 2D/3D quad elements it is possible to implement an integration type that handles an arbitrary amount of Gauß integration points and weights (algorithm computing the points and weights). The definition of visualization cells for 1D and 2D/3D quads can also be implemented in a generic way. **The only handicap are the enum classes like IntegrationTypeEnum.h::eIntegrationType. There you still need to specify the number of integration points manually.**  Are there some ideas how to replace or remove these implementations (e.g. in StructureBaseIntegrationTypes.cpp)

**Comment by TTitscher** [comment]
Closely related to both #35 (definition of the corresponding visualization cells) and #34 (API change to get rid of said enum).

**Comment by Psirus** [comment]
Imho that's a good idea. Maybe we can get rid of the enum with a shared pointer again, without changing everything else (visualization etc.) for now?

**Comment by pmueller2** [comment]
Solved in PDE.
