### ISSUE TITLE
ContinuumBoundaryElement

### ISSUE THREAD

**Issue by potto1** [nutofem/nuto#41]
Would be nice to only assemble the relevant nodes and skip the zero entries of the nodes lying not on the boundary. Also relevant for Contact elements.

**Comment by TTitscher** [comment]
This would correspond to a, say, __SurfaceElement__ that is not related to its underlying continuum element, right?

The `SurfaceElement3D` or `SurfaceElement<3>` contains nodes of dimension 3. These may be shared with some `ContinuumElement<3>`s. However, the interpolation and integration is of dimension 2. This allows moving the `Load` stuff (basically a surface integration as well) to the SurfaceElements.

But: This `SurfaceElement` cannot calculate normal derivatives of nodal values. Can you think of relevant cases where this is needed? If so, we can keep the `ContinuumBoundaryElement` for those cases. If not, we could get rid of it. I needed this case once for experimenting with boundary conditions of the gradient damage model. Did not work as expected though and can be removed.

**Comment by TTitscher** [comment]
Btw: related to issue #28

**Comment by potto1** [comment]
We could implement the SurfaceElement as already done for IGALayer elements in the iga branch. The BoundaryElement could be used for Contact formulation, so I think removing the zeroes from BoundyElement would be nice too.

**Comment by potto1** [comment]
I am fine with both ))

**Comment by TTitscher** [comment]
I want to apply a constant pressure on some SurfaceElements. It is trivial to obtain a vector normal to the surface, even for curved surfaces. But how can we define the direction _inwards_? Is this something that is defined when creating the elements? How?

**Comment by pmueller2** [comment]
I think for such signed direction things it is necessary to agree on some sign conventions like: Volume elements should be created so that the jacobian determinant is always positive or Surface elements should be created so that they have a oriented boundary and the right hand rule is valid for the normal vector.
If you then create a surface using several surface elements you could check that the boundaries that join two elements have opposite directions. I think this would assure that all are oriented in one direction. (This is possibly not what you asked for but it is also not so far off I think)

**Comment by TTitscher** [comment]
You might have closed this issue by accident. 

My question is: How can we implement the orientation (INWARDS / OUTWARDS). But it should somehow be possible that, in the end, it looks like this:
~~~cpp
Group<ContinuumElement> elementsOnTheSurface;
Group<Node> surfaceNodes;
auto surfaceElements = NuTo::SurfaceElementsCreate(elementsOnTheSurface, surfaceNodes, eOrientation::INWARDS);
~~~
Do you like such an interface?

Maybe, in the majority of cases, this is done via gmsh and the boundary elements are just another physical element group.

**Comment by joergfunger** [comment]
Why do we need this inwards/outwards? The current setup is that all Surfaces should be oriented the way that when calculating the normal based on the right hand rule, the normal should always point outwards. By changing the sign of the load function, a force pointing inwards can be calculated.

**Comment by TTitscher** [comment]
In general, one can define a surface element without a corresponding continuum element. If it happens to actually be the boundary of an element, how can it know its orientation with respect to that element?

Imagine I use the meth generator.
First, I create a 1D grid of 10 surface elements. Afterwards, create a 2D grid, 10x10 elements. Then, merge overlapping nodes. Now, if I want to apply pressure inwards, where is inwards?

We could define some ordering. Say, if you create a mesh from point 1 to point 2 and walk along this path, inwards is left. So it is the users job to define his grid, either from point 1 to point 2 or from point 2 to point 1. (Sorry for one based indexing, hope you could follow nonetheless...)

How would this look like in 3D?

**Comment by Psirus** [comment]
Solved in PDE.
