### ISSUE TITLE
Time dependent loads

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#46]
Time dependent loads can be set in the time integration scheme via
~~~cpp
    //! @brief sets a scalar time dependent multiplication factor for the external loads
    //! @param rLoadRHSFactor ... first row time, second row scalar factor to calculate the external load (linear interpolation in between,  afterwards linear extrapolation)
    void SetTimeDependentLoadCase(int rLoadCase, const Eigen::MatrixXd& rLoadRHSFactor);
~~~
Problems:
- cryptic `rLoadRHSFactor` matrix
- only one load matrix - impossible to apply F(x_left) = F0 sin(t) _and_ F(x_right) = F0 cos(t)
- outdated interface - still uses load cases that were removed some time ago
- implemented only for the mechanics problem

Solution:
- time dependent load functions `std::function<double(double)>` for each load, similar to _Constraints_
- possibly in combination with #28 and #41 (load integration in boundary/surface elements)
- possible interface:
~~~cpp
/* main */
std::function<double(double)> loadFunction = [=](double t){return std::cos(t);};
auto load = NuTo::Load::Pressure(NuTo::Group<SurfaceElement> elements, Pressure(5.), loadFunction);
structure.Load().Add(load);
~~~

**Comment by joergfunger** [comment]
The only question might be, if this scalar function could be replaced by something that represents the external load vector better (with this scalar equation, all load values have to be scaled identically over time).
Could we define a general interface to allow an evolution as a function of F(x,t) != F(x)*F(t)?

**Comment by joergfunger** [comment]
The second remark is related to the question, if we want to consider the external loads as a simple (not dependent on x) specialization of the standard integrands, so in this case, there is no real difference between a standard internal (force) vector and the external load vector.

**Comment by TTitscher** [comment]
In my naive approach, you could define as many scalar functions as you like. In my example above, just add a new load function for a different group.
~~~cpp
std::function<double(double)> loadFunction2 = [=](double t){return std::sin(t);};
auto load = NuTo::Load::Pressure(NuTo::Group<SurfaceElement> elements2, Pressure(42.), loadFunction2);
...
~~~

But I like the idea of F(__x__, t)! Do you think that the overhead of this (calculate __x__ for each IP) is noticeable? If so, we can have multiple "IntegrandNtF" (naming since they integrate N^T F(...) ): `IntegrandNtFxt, IntegrandNtFx IntegrandNtF`. And we can and should change the names. But maybe you get my idea.

**Comment by joergfunger** [comment]
In the pde concept, the integrand is always evaluated (not just scaled with a time factor). When joining internal and external loads into a single framework (cell/integrand), then there is no overhead for the case where x is not required (since the integrand itself determines what is to be calculated) - so this would mean that we require (as proposed IntegrandNtFxt IntegrandNtF). The IntegrandNtFx is imo not required since the only difference is that the time t is not used - the overhead is certainly very limited.
