### ISSUE TITLE
Unused functions and members

### ISSUE THREAD

**Issue by phuschke** [nutofem/nuto#47]
Many classes have lots of unused functions and/or members.

**Detection of unused functions and members**
Most IDEs can detect usages of functions and members. It is usually safe to delete them as they have no purpose. However, there are exceptions. 

1. If a function is only called in a python test, some IDEs will not detect its usage
2. If a member is only used in a constructor (e.g. initialization to its default value), it is used but has no purpose.

**Good practice**: Members of a primitive data type should not be initialized to their default value in the initializer list of a constructor but directly when declared. This makes it easier to check for unused members and speeds up the search for their default value.

**Classes are cluttered with accessors and mutators** 
Many of the functions that are unused are accessors and/or mutators and for a **good reason**! Why do we want to access members of an object? We would much rather have the object _do_ something for us with its members. Of course, there are exceptions where accessors are necessary but those are rare and I do not think we should clutter classes with unused accessors.

> Objects expose behavior and hide data. This makes it easy to add new kinds of objects
> without changing existing behaviors. It also makes it hard to add new behaviors to existing
> objects. Data structures expose data and have no significant behavior. This makes it easy to
> add new behaviors to existing data structures but makes it hard to add new data structures
> to existing functions.
Robert Cecil Martin

**Endeavors**
- Are there any good reasons to keep unused functions you can think of?
- What do you think of initializing a primitive member to its default value directly when declared?

**Comment by TTitscher** [comment]
> This makes it easier to check for unused members and speeds up the search for their default value.

This might dependent on your workflow or your IDE. If I edit a cpp file, I can perform a simple text search (no fancy code model required) in the file and the first use of a member variable often is its initialization in the ctor. I donno, as long as it is consistent, I'm fine with it. 

> Are there any good reasons to keep unused functions you can think of?

- Someone implements a new method he needs for his private main files and forgets to write a test.
- There was no test in the first place and still we trust in these methods in private main files.

I'm still thinking about the accessors... It certainly is a valid principle, objects do stuff, data structures only provide access to its data. IMO this can be done in a good designed environment. If we look at the time integration classes, a lot of other principles are violated. The class has multiple purposes, time discretization, post processing to vkt, post processing of single results, newton-raphson algorithm, line search algorithm. And then it has a bunch of member variables to control the different purposes. On top, it has a bunch of methods that violate polymorphism. E.g. NewmarkDirect::CalculateCriticalTimeStep is not meaningful for implicit schemes. Why is it in the time integration base class? What is the purpose of time integration base anyways? 

Ok, not the purpose of this issue, sorry. Unused getter/setter are certainly not the main problem, but we have to start somewhere. And unused methods are dead code, delete it. Maybe collect them in an issue beforehand to give people, who privately use them, a deadline to write test for them.
