### ISSUE TITLE
Apply clang-format to all cpp and h files

### ISSUE THREAD

**Issue by phuschke** [nutofem/nuto#51]
**Problem**
We agreed on a code formatting style that is defined in _.clang-format_. However, many files have not been formatted yet. This is a problem when I want to remind myself of the changes I made (`git diff`) before I write my commit messages because git then tells me that every line has been edited.

**Solution**
I suggest that we agree on a final version of a code formatting style and run clang-format recursively on all files:

`find -name '*.cpp' -o -name '*.h' | xargs clang-format -i`

**Comment by TTitscher** [comment]
Just to make it easier for everyone, some resources 
- [our .clang-format file](https://github.com/nutofem/nuto/blob/master/.clang-format)
- [documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
- [configurator](https://clangformat.com/)
- [IDE integration](https://github.com/nutofem/nuto/blob/master/doc/dev/CodingStyle.md)

**Comment by TTitscher** [comment]
A senior software guy, I know, told me their policy. If you want to perform changes to a file and apply style changes, you perform two commits. First, a __beautify commit__ (marked as such) that can be ignored by the CI and the reviewers. Second, your actual changes in the corresponding file. This could be a intermediate solution.

**Comment by Psirus** [comment]
I'd vote just to do this once, so that we don't have 100 beautify commits over the next months. And if it happens after that, we use the method suggested by senior software guy.

**Comment by Psirus** [comment]
And while we're at it, also run

    find -name '*.cpp' -o -name '*.h' -o -name '*.py' -o -name '*.cmake' | xargs sed -i -r '/.*\$Id\$.*/d'

please. What happens is left as an exercise to the reader :)

**Comment by Psirus** [comment]
Done
