### ISSUE TITLE
More Ctor() work, less Set()

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#6]
A lot of classes have an empty constructor with `Set*` methods for their members. This makes it hard to ensure a valid state of the class. E.g.:
- material parameters in the constitutive laws
- ctor of ElementDataConstitutiveBase: `mConstitutiveLaw = nullptr;`
  However, you can provide corresponding `Set` methods on the `Structure` level. That is also convenient for the python interface. 
### Option 1:

@phuschke suggested an alternative for the constitutive laws. The constitutive law object is constructed in your main file and the pointer is passed to the structure. If you expose the constitutive law to swig, this should work with python as well. Downside: The structure no longer owns the constitutive law. Maybe this could affect the serialization. Or you do some weird workaround like:

```
ConstitutveBase* Structure::SetConstitutiveLaw(ConstutitveBase* rConstitutiveLaw)
{
  int id  = FindUnusedId();
  mPtrMap.insert(id, rConstitutiveLaw.clone());
  return mPtrMap.at(id);
}
```

or maybe better as template:

```
template<typename T>
T* Structure::SetConstitutiveLaw(T& rConstitutiveLaw)
{
  int id  = FindUnusedId();
  mPtrMap.insert(id, new T(rConstitutiveLaw)); // or whatever the syntax is...
  return mPtrMap.at(id);
}
```

Drawback: You still have a copy of the constitutive law in your main file that should not be used after adding it to the structure. 
### Option 2:

another possibility: Only accept temporaries via the &&

```
template<typename T>
T* Structure::SetConstitutiveLaw(T&& rConstitutiveLaw)
{
  int id  = FindUnusedId();
  mPtrMap.insert(id, new T(rConstitutiveLaw)); // move construction, I guess
  return mPtrMap.at(id);
}
```

or

```
template<typename T>
std::pair<int, T*> Structure::SetConstitutiveLaw(T&& rConstitutiveLaw)
{
  int id  = FindUnusedId();
  mPtrMap.insert(id, new T(rConstitutiveLaw)); // move construction, I guess
  return std::make_pair<id, mPtrMap.at(id)>;
}
```

This could be called via:

```
myStructure.SetConstitutiveLaw(LinearElasticEngineeringStress(30000, 0.3));
```

but 

```
LinearElasticEngineeringStress myLaw(30000, 0.3);
myStructure.SetConstitutiveLaw(myLaw); 
```

would fail to compile. Not sure about swig though.
### Option 3:

c++11 provides the "perfect forwarding" (compiler magic eliminates temporaries, performance gain not crucial for our case) and looks like:

```
template<typename T, typename... Args>
void Structure::SetConstitutiveLaw(Args&&... rCtorParameters)
{
  int id  = FindUnusedId();
  ConstitutiveBase* ptr = new T(std::forward<Args>(rCtorParameters)...);
  mPtrMap.insert(id, ptr);
  return mPtrMap.at(id);
}
```

This could be called via

```
myStructure.SetConstitutiveLaw<LinearElasticEngineeringStress>(30000,0.3);
```

Drawbacks: 
- Most likely no swig version of this.
- There will be no help (autocompletion) from the IDE
## Your turn. :)

Obviously, this could be applied to any other class, like Sections, IntegrationTypes, InterpolationTypes, Constraints, ...

**Comment by phuschke** [comment]
### Option 4.Huschke

I am a big fan of option 2. We could use const instead of temporaries without causing safety issues. Here are some minor improvements:
- `insert` => `emplace`
- `emplace_hint` for maps that insert at a position that is known a priori
- `boost::ptr_map<int, Base>` => `std::map<int, std::unique_ptr<Base>>`

```
#include <map>
#include <iostream>
#include <memory>

class Base
{
public:
    virtual ~Base() = default;
    virtual void bla() = 0;
};

class Child: public Base
{
public:
    Child(int a):Base(),mA(a){}
    void bla() override
    {std::cout << "awesome " << std::endl;}
private:
    const int mA;
};

template<class T>
void func(const T& rChild)
{
    std::map<int, const std::unique_ptr<Base>> myMap;
    myMap.emplace_hint(myMap.end(), 3, std::make_unique<T>(rChild));
    myMap.at(3)->bla();
}

int main()
{    
    const Child c(32);
    func(c);
}
```

Nice idea to template the function :-)

**Comment by TTitscher** [comment]
If all the Child members are const, this is no problem, i guess. For other classes, this might not be the case. Say, you put `func` in a class and add a `Set` function to Child. You could to something like

```
int main()
{
    Child c(32);
    Structure s;
    s.func(c);
    s.CallBla(); // cout: awesome 32

    c.Set(5); // this is tempting
    s.CallBla(); // cout: awesome 32
}
```

This behavior may not be expected. 

If you only accept temporaries via `&&` this would not be possible. 

```
int main()
{
    Structure s;
    s.func(Child(32)); // no possibility to change Child
    s.CallBla();  // cout: awesome 32
}
```

or if you implement a return value: `T* func(T&& rChild)`

```
int main()
{
    Structure s;
    Child* c = s.func(Child(32));
    c.Set(5);
    s.CallBla(); // cout: awesome 5
}
```

**Comment by phuschke** [comment]
I completely agree with you. The suggestion was just to address the possible swig issue you mentioned previously. 

Can you think of any member variables that should not be const? A setter would be redundant in that case.

**Comment by TTitscher** [comment]
I just tried it, there is no problem with the xvalues (`T&&`) in swig. However, it is somehow treated as a normal reference, so in python you could still instantiate an object an pass it via reference. Maybe we have to define the importance of the python interface first. But this is a separate issue...

As for non-const members: I am not sure when it comes to constitutive laws. But I wouldn't design the pattern in a way that forbids Setters in general. ..

**Comment by joergfunger** [comment]
In my opinion, we should not expose the constitutive laws to the python/user level (not developer level). This would either require to expose only a part (without the evaluate methods) to python, or to write wrappers for the maps we use as input/output to the constitutive law. Both options are not what I prefer, since the constitutive laws only make sense in combination with the structure they belong to. Allowing for a separate instantiation (without a structure), would also require exposing the header files of the constitutive laws to the (end/python)-user.
Continuing this approach would also mean, we instantiate everything (elements, ip-data, nodes) on the main-file level, and then just add the pointers to the structure. But then we would use ptr (e.g. node ptrs in the element class ) instead of ids (I do not feel like ptrs being the right thing to be exposed, since this changes in every run).

**Comment by TTitscher** [comment]
Well, I am not sure on how to deal with this problem. Having a `Structure` that controls everything provides a nice interface. On the other hand, every method that should be accessible by the user has to written at least twice. 1) The real implementation in the specific class and 2) an simple forward method from the `Structure`. 
An if I have a look at the test files, this is usually not done. Instead, you'll find something like

```
// 1st example
NodeBase* node = myStructure.GetNode(42);
node->GetSetNonlocalEqStrain(0.42);

// 2nd example
GradientDamageLaw* law = <cast>myStructruce.GetConstitutiveLaw(42);
law.GetDamage(.42);
law.GetDamageDerivative(.42);
```

instead of

```
// 1st
myStructure.NodeSetNonlocalEqStrain(42, 0.42);

// 2nd
myStructruce.ConstitutiveLawGetDamage(.42);
myStructruce.ConstitutiveLawGetDamageDerivative(.42);
```

(These are examples from my own files, because I don't want to blame anyone else, but everyone does it... )
The first example can be rewritten quite easily using more general access methods like
`Structure::NodeSetDof(Node::NONLOCALEQSTRAIN, .42)`.
The second example cannot be solved in general. For proper testing, you have to expose all methods of all constitutive laws (1st method, implementation) to the base class (2nd method) and write a forwarding method in the Structure (3rd method). I somehow feel, that this is not the proper way...

**Comment by Psirus** [comment]
Solved in PDE.
