### ISSUE TITLE
Test files

### ISSUE THREAD

**Issue by joergfunger** [nutofem/nuto#7]
The current test files are not appropriate for testing, since errors are always global and the run time is way too long. We should try to have a more specific and fine grained test setup, so that someone not familiar with that specific problem directly sees where the problem is (currently, we only realize that there is a problem).

**Comment by Psirus** [comment]
As I've now pushed the "new" constitutive input and output, maybe you can have look at the unit tests I've written along the way. They are much simpler, and all of them (six so far) run in 0.03s on my system. You can try it yourself with

```
ctest -R unit
```

Note: you need to have `ENABLE_UNIT_TESTS` set to `ON`. I hope this is sort of what you had in mind and that we can expand the use of unit testing.

**Comment by joergfunger** [comment]
This is a very good starting point. Everyone should check, if his test files are really test files, or if they could be simplified and decomposed into several unit tests (often, the test files are just examples, not really tests). In addition, we need a flexible way of having a flag to enable/disable tests that are supposed to fail (because something has been changed, but the corresponding tests is not yet fixed, or a restructuring of the source code lead to some features that do not currently work). In this case (where a test is supposed to fail), there should be someone directly assigned (via a ticket or directly in the source code) to be responsible for fixing this issue in the near future.

**Comment by TTitscher** [comment]
Commit 707adee wraps this ctest command. You can now run
`make unit`

**Comment by Psirus** [comment]
I've added a "flexible way" of ignoring a test in commit 6dd5000. Now you can simply add the test that is supposed to fail to the file `CMakeScripts/CTestCustom.cmake`. 

Can this issue be closed then?

**Comment by Psirus** [comment]
In a series of commits, starting with c7d517aa919495b273cd4aa036c55c8d0909f3d3 and finding a temporary end at 4359f4a22bc6ae6e4e1e112d34d46ab3036913f3, the tests have been separated into integration tests and unit tests. Therefore I'm closing this now.
