### ISSUE TITLE
Refactor NodeBase and NodeDof

### ISSUE THREAD

**Issue by szorn85** [nutofem/nuto#73]
**Problem:**

- NodeBase is an abstract class that only has one child. 

- Many functions throw an exception instead of being pure virtual

**Reason:**

- NodeDof used to be templated over various DOFs

**Solution:**

- Merge NodeBase and NodeDof into a single class to improve readability.

**Comment by TTitscher** [comment]
Sometimes it is advantageous to have an interface for better testing. You could pass a fake NodeBase into a function that requires one. 
I foresee major changes in the node regarding pde and its dof separation (one node per dof type).

**Comment by Psirus** [comment]
Solved in PDE.
