### ISSUE TITLE
Better exception handling

### ISSUE THREAD

**Issue by vhirtham** [nutofem/nuto#81]
At the moment we are basically using the NuTo::MechanicsException for nearly everything. While this is totally fine in general, it would be nice to have some way to distinguish between different types of exceptions for testing purposes. If one of my functions can throw 2 or more exceptions and I want to test, if the "right" one is thrown, the only possibility to separate them is to check the error string which is suboptimal for multiple reasons.

In the STL there are different kind of exceptions derived from std::exception:

http://en.cppreference.com/w/cpp/error/exception

Maybe we can introduce some additional exception types derived from NuTo::MechanicsException or NuTo::Exception like in the STL.

**Comment by TTitscher** [comment]
IMO you can and should define them as you wish. But they have to be way more specific than the previous `MathException` or `OptimizeException`. 
E.g., for the newton raphson algorithm, I quickly implemented [`NuTo::NewtonRaphson::NoConvergence`](https://github.com/nutofem/nuto/blob/master/src/math/NewtonRaphson.h#L12). So this would be my proposal...

**Comment by Psirus** [comment]
I would agree with that. If you need to catch a specific exception, like "Newton-Raphson did not converge", create just that. Imho one probably never knows how to handle *any* `NuTo::RuntimeException` or `NuTo::InvalidArgument` exception. So either create e.g. `NuTo::NegativeYoungsModulus` or just throw `NuTo::Exception`, expecting it to be "fatal".
