### ISSUE TITLE
Node design

### ISSUE THREAD

**Issue by TTitscher** [nutofem/nuto#9]
I just implemented a new API for `class NodeBase`. (Don't know if you got the push-mail. I didn't, for some reason... anyways) It now contains (amongst others) the following dynamic access methods for the DOF values

``` c++
const Eigen::VectorXd& Get   (Node::eDof rDof, int rTimeDerivative) const; // gets the dof values
void                   Set   (Node::eDof rDof, int rTimeDerivative, const Eigen::VectorXd& rDofs); // sets the dof values
int                    GetNum(Node::eDof rDof) const; // gets the number of dofs
int                    GetDof(Node::eDof rDof) const; // gets the global dof number
```

This results in significantly less code, additional methods for possible new DOF types are not required. Additionally, the DOF values are always dynamic eigen vectors. So far, it is alright, I guess.

The issue is implementation in `class NodeDof`, more precisely, how the data is stored. Currently, each node has three members

``` c++
int mNumTimeDerivatives;
std::unordered_map<Node::eDof, std::vector<Eigen::VectorXd>, (hash function)> mDofValues; //std::vector for the time derivatives
std::unordered_map<Node::eDof,             Eigen::VectorXi,  (hash function)> mDofNumbers;
```

Problems:
- Not all nodal information is a DOF (e.g. COORDINATES). No dof number required.
- Not all nodal information needs time derivatives (e.g. COORDINATES)
- mNumTimeDerivatives unnecessary, could be removed easily, it is only used for assertions.

How to address these problems:
- Provide seperate members? Would this result in:
  - mValuesDof
  - mValuesNoDofWithTimeDerivative
  - mValuesNoDofNoTimeDerivative
- Add seperate classes and go back to the inheritance "diamond of death"?
- Just add a mCoordinates member that can be empty if the node has no coordinates?
  - This would be OK, but can we think of node information (other than coordinates) that needs no DOF number and/or no time derivatives?

**Comment by joergfunger** [comment]
This is good news, since it simplifies our nodes significantly. You are currently storing a mDofValues as std::vectorEigen::VectorXd. This directly includes  the number of time derivatives
mDofValues.size(). So the additional mNumTimeDerivatives can be removed, and does not have to be a template argument. We could then dynamically allocate the time derivates for each dof type separately, so coordinates would get a zero and all the others based on what is required. This would simplify class structure, since then coordinates are not special.

**Comment by TTitscher** [comment]
Sounds OK to me. However, the 
`int GetNumTimeDerivatives()` needs to be changed to 
`int GetNumTimeDerivatives(Node::eDof)` since each dof type may have a different number of stored time derivatives. But the problem can be solved this way.

The issue with storing unnecessary dof numbers remains. We could add a `bool IsDof` flag to the constructor. Idea:

``` c++
struct NodeDofInformation 
{
    int mNumTimeDerivatives
    int mDimension
    bool mIsDof
};

/* in class NodeDof */
NodeDof(std::map<Node::eDof, NodeDofInformation> rDofInformationMap)
{
    // allocate mValues based on dimension and time derivatives
    // allocate mDofNumbers based on dimension and IsDof
}
```

And we should think about renaming. Maybe the old enum name `Node::eAttribute` was not that bad... This might be related to issue #2.

**Comment by joergfunger** [comment]
Should we force the number of time derivatives to be constant for all dofs (apart from coordinates)? In this case, we could use a template parameter and use a fixed size array. We could also make the number of coordinates another template parameter and store the coordinates as a separate entity (not within the map). Do we want to have the option of having other dofs (such as e.g. temperature) not being dofs (in case we just prescribe nodal values, e.g. temperature and then use a combined mechanics/thermal solution, where only the interaction is considered? 
This seems to be only a rare case. However, when looking at storing dofs that are not really nodal values (such as for example the material parameters or time discretizations in the PGD, external temperatures) this might happen.

**Comment by TTitscher** [comment]
The idea of the redesign was to increase the flexibility. I think, experience shows that many assumptions we make only hold for some months or so. After that, someone has a use-case that was not intended in the first design. The assumptions here would be 
- numTimeDerivatives = const
- COORDINATES = only non-dof

At the moment, I think they are OK, but as Jörg said, maybe they are not valid for PGD nodes...

So, I vote for the most flexible design, e.g. shown in my comment above. Plus, I do not see the benefit of the templates here. Maybe faster asserts. Downside: Annoying `NodeCreate`...
