### ISSUE TITLE
Handling of NuTo mesh file

### ISSUE THREAD

**Issue by BRiedel314** [nutofem/nuto#91]
To solve a global system in parallel with the help of Trilinos each process has to read a mesh file (see #89) to build a local system corresponding to the subdomain specified by this file. The local assembled matrices and vectors have to be converted to Trilinos matrix/vector formats. With the help of the global DOF numbering given in the mesh file Trilinos is able to compute and solve the global system. Therefore different functionalities have to be implemented:

- [ ] Trilinos solve 
  - [ ] reading of NuTo mesh files/extracting necessary information
  - [ ] building Trilinos internal data structures (maps, graphs)
  - [ ] assemble local matrices with NuTo methods and convert to Trilinos formats
  - [ ] solution of global system (how to incorporate constraints?)

**Comment by joergfunger** [comment]
See #92
