### ISSUE TITLE
Incorporation of IGA and sub-/superparamtric formulations

### ISSUE THREAD

**Issue by BRiedel314** [nutofem/nuto#92]
If it is possible to solve different systems in paralle with the help of the NuTo mesh file format #89 and Trilinos, holds the same (or similar) procedure for furhter formulation like IGA or sub-/superparametric formulations?
 - Additional information in the mesh file?
 - adaption in handling functionalities #91?

**Comment by joergfunger** [comment]
The mesh file is no longer favored. Instead, one process performs the application of constraints including the numbering, decomposes the mesh into substructures, and sends each domain via boost::serialize and boost::mpi to the MPI-process that performs the calculation. These serialized mesh files could also be reread (for example as restart files or if the mesh partitioning should not be done on each run, i.e. when only modifications of parameters that do not affect the mesh are applied.)
