### ISSUE TITLE
Format cmake

### ISSUE THREAD

**Issue by phuschke** [nutofem/nuto#95]
## General
Soon we will start using [coala](https://coala.io/#/home) as a tool for static analysis (see #65).

## Problem
CMakeLintBear yields _a lot_ of warnings that we should probably address first before we add the bear in the proposed .coafile (see [coala branch](https://github.com/nutofem/nuto/tree/coala)). 

## Solution
- [x] Find a tool that formats cmake files
- [x] Add CMakeLintBear to .coafile

**Comment by Psirus** [comment]
Done in coala branch.
